[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=0.6.3",
    "groq>=0.18.0",
    "pandas>=2.2.3",
    "streamlit>=1.42.0",
]
